#!/usr/bin/env python2

# Copyright (c) 2012 Jeppe Ledet-Pedersen <jlp@satlab.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

import sys
import time
import os.path
import argparse
import copy

import bluebox
import fec

subcommands = {}
def subcommand(*args, **kwargs):
	def _decorator(func):
		nargs = list(args)
		help = nargs[0]
		nargs[0] = func.__name__
		kwargs["help"] = help
		_option = (nargs, kwargs)
		if not subcommands.has_key(func.__name__):
			subcommands[func.__name__] = {}
		subcommands[func.__name__]["sub"] = _option
		subcommands[func.__name__]["func"] = func
		if not subcommands[func.__name__].has_key("args"):
			subcommands[func.__name__]["args"] = []
		return func
	return _decorator

def argument(*args, **kwargs):
	def _decorator(func):
		_option = (args, kwargs)
		if not subcommands.has_key(func.__name__):
			subcommands[func.__name__] = {}
		if not subcommands[func.__name__].has_key("args"):
			subcommands[func.__name__]["args"] = []
		subcommands[func.__name__]["args"].insert(0, _option)
		return func
	return _decorator

colors = {"gray": 30, "red": 31, "green": 32, "yellow": 33,
	  "blue": 34, "magenta": 35, "cyan": 36, "white": 37}

enable_colors = False

def colorize(color, text, *args, **kwargs):
	print("\033[{0}m{1}\033[0m".format(colors[color] if enable_colors else 0, text), *args, **kwargs)

def parse_frequency(s):
	prefixes = {'K': 1e3, 'M': 1e6, 'G': 1e9}
	mult = 1
	if s.lower().endswith("hz"):
		s = s[:-2]
	for prefix in prefixes.keys():
		if s.upper().endswith(prefix):
			mult = prefixes[prefix]
			s = s[:-1]
			break
	try:
		hz = int(float(s)*mult)
	except:
		raise argparse.ArgumentTypeError("{0} is not a valid frequency".format(s))

	return hz

def parse_int(s):
	try:
		integer = int(s, 0)
	except:
		raise argparse.ArgumentTypeError("{0} is not a valid integer".format(s))

	return integer

def parse_power(s):
	try:
		power = int(s)
		if power < 0 or power > 63:
			raise ValueError
	except:
		raise argparse.ArgumentTypeError("power must be between 0 and 63")

	return power

def bar(value, minimum=-130, maximum=-47, width=40):
	value = max(value, minimum)
	value = min(value, maximum)

	progress = (value+abs(minimum))*width/(maximum+abs(minimum))
	bar = "[" + progress * "#" + (width-progress) * " " + "]"

	return bar

@subcommand("set device in DFU mode")
def dfu(args, bb):
	bb.dfu()

@subcommand("update device firmware")
@argument('filename', help="firmware file to flash")
def update(args, bb):
	bb.update(args.filename)

@subcommand("reset BlueBox")
def reset(args, bb):
	bb.reset()

@subcommand("show RF silicon revision")
def version(args, bb):
	ver = bb.version()
	print(hex(ver))

@subcommand("show current RSSI reading in dBm")
def rssi(args, bb):
	rssi = bb.rssi()
	print("{0} dBm".format(rssi))

@subcommand("continuously show RSSI reading")
@argument("-t", metavar="samples", dest="samples", type=int, help="number of samples per frequency", default=10)
def signal(args, bb):
	minimum = -130
	maximum = -47
	width = 40

	while True:
		try:
			rssi = bb.rssi(args.samples)
			sys.stdout.write("\r{0} {1} dBm ".format(bar(rssi), rssi))
			sys.stdout.flush()
			time.sleep(0.1)
		except KeyboardInterrupt:
			print()
			sys.exit(0)
		except Exception as e:
			print(e)
			break

@subcommand("receive packets and print to screen")
@argument('-d', '--decode', dest="decode", help="decode packets", action='store_true', default=False)
@argument('-k', '--key', dest="key", help="HMAC-SHA1 key", default=None)
@argument('-r', '--retransmit', dest="retransmit", help="Enable retransmission of received data", action='store_true')
def receive(args, bb):
	count = 0
	if args.decode:
		if not args.key:
			subcommands[args.subparser]["parser"].error("-d requires a key passed with -k")
		ph = fec.PacketHandler(args.key)
	while True:
		bit_corr = 0
		byte_corr = 0
		data, rssi, freq = bb.receive()
		if data is None:
			continue

		if args.decode:
			try:
				data, bit_corr, byte_corr = ph.deframe(data)
			except:
				byte_corr = -1
		
		color = "red" if byte_corr == -1 else "yellow" if bit_corr or byte_corr else "green"
		colorize(color, "{0:03} {1:.2f} RX ({2:03d}/{3:03d}) {4:4} dBm {5:+5d} Hz ({6:03}) '{7}'".format(count, time.time(), bit_corr, byte_corr, rssi, freq, len(data), data.encode("hex")))
		count += 1

		if byte_corr == 0 and args.retransmit:
			bytes = data
			colorize("blue", "{0:03} {1:.2f} TX ({2}) '{3}'".format(count, time.time(), len(bytes), bytes.encode("hex")))
			if args.decode:
				bytes = ph.frame(bytes)
			bb.transmit(bytes)

@subcommand("transmit packet data")
@argument('packet', help="packet hex string to transmit", nargs="+")
@argument('-r', '--wait-reply', dest="wait_reply", help="wait for reply", action='store_true', default=False)
@argument('-e', '--encode', dest="encode", help="encode packets", action='store_true', default=False)
@argument('-d', '--decode', dest="decode", help="decode packets", action='store_true', default=False)
@argument('-k', '--key', dest="key", help="HMAC-SHA1 key", default=None)
@argument('-c', '--continuous', dest="continuous", help="Continuously send data", action="store_true")
@argument('-s', '--switch', dest="switch", metavar="MS", help="Switching time in ms", type=int, default=0)
@argument('-n', '--number', dest="number", help="Repeat transmission NUMBER times", type=int, default=1)
def transmit(args, bb):
	continuous = True
	tx_count = 0
	rx_count = 0

	if args.encode or args.decode:
		if not args.key:
			subcommands[args.subparser]["parser"].error("-e/-d requires a key passed with -k")
		ph = fec.PacketHandler(args.key)

	while continuous:
		for i in range(0, args.number):
			for packet in args.packet:
				bytes = packet.decode("hex")
				colorize("blue", "{0:03} {1:.2f} TX ({2}) '{3}'".format(tx_count, time.time(), len(bytes), bytes.encode("hex")))
				if args.encode:
					bytes = ph.frame(bytes)

				if args.verbose:
					print("Transmit data:")
					print(ph.hexdump(bytes))

				bb.transmit(bytes)
				tx_count += 1
				if args.wait_reply:
					data, rssi, freq = bb.receive()
					if data is None:
						colorize("yellow", "Timeout while waiting for reply")
					else:
						bit_corr = 0
						byte_corr = 0

						if args.verbose:
							print("Receive data:")
							print(ph.hexdump(data))

						if args.decode:
							try:
								data, bit_corr, byte_corr = ph.deframe(data)
							except:
								byte_corr = -1

						color = "red" if byte_corr == -1 else "yellow" if bit_corr or byte_corr else "green"

						colorize(color, "{0:03} {1:.2f} RX ({2:03d}/{3:03d}) {4:4} dBm {5:+5d} Hz ({6:03}) '{7}'".format(rx_count, time.time(), bit_corr, byte_corr, rssi, freq, len(data), data.encode("hex")))
						rx_count += 1

				continuous = args.continuous
				time.sleep(args.switch/1000.0)

testmode_desc = """
This command puts the BlueBox in testmode and transmits a test signal.

The available test signals are:
  carrier    continuously transmit carrier frequency
  0101       transmit sequency of alternating 0's and 1's
  high       transmit 1 frequency
  low        transmit 0 frequency
  pn9        transmit PN9 pattern
  syncword   continuously transmit programmed syncword
  off        disable test pattern
"""

@subcommand("put device in test mode", description=testmode_desc)
@argument('mode', help="test signal", choices=("carrier", "high", "low", "pn9", "1010", "syncword", "off"))
@argument('-l', '--limit', type=int, metavar="seconds", help="stop after limit seconds")
def testmode(args, bb):
	if args.mode == "carrier":
		bb.testmode(bb.TESTMODE_OFF)
		bb.tx_mode()
	elif args.mode == "high":
		bb.testmode(bb.TESTMODE_PATTERN_HIGH)
		bb.tx_mode()
	elif args.mode == "low":
		bb.testmode(bb.TESTMODE_PATTERN_LOW)
		bb.tx_mode()
	elif args.mode == "pn9":
		bb.testmode(bb.TESTMODE_PATTERN_PN9)
		bb.tx_mode()
	elif args.mode == "1010":
		bb.testmode(bb.TESTMODE_PATTERN_1010)
		bb.tx_mode()
	elif args.mode == "syncword":
		bb.testmode(bb.TESTMODE_PATTERN_SWD)
		bb.tx_mode()
	elif args.mode == "off":
		bb.testmode(bb.TESTMODE_OFF)
		bb.rx_mode()

	if args.mode != "off" and args.limit is not None:
		time.sleep(args.limit)
		bb.testmode(bb.TESTMODE_OFF)
		bb.rx_mode()

@subcommand("set device in transmit mode")
def txmode(args, bb):
	bb.tx_mode()

@subcommand("set device in receive mode")
def rxmode(args, bb):
	bb.rx_mode()

@subcommand("get or set device frequency")
@argument('frequency', help="requested frequency", type=parse_frequency, nargs="?", default=None)
def frequency(args, bb):
	if args.frequency is not None:
		bb.set_frequency(args.frequency)
	else:
		print(bb.get_frequency())

@subcommand("get or set device bitrate")
@argument('bitrate', type=int, help="requested bitrate", nargs="?", default=None)
@argument("-m", "--automod", action="store_true", help="Automatically adjust modulation index")
def bitrate(args, bb):
	if args.bitrate is not None:
		if args.automod:
			oldbit = bb.get_bitrate()
			oldmod = bb.get_modindex()
			mod = max(oldmod * oldbit/args.bitrate, 1)
			bb.set_modindex(mod)
		bb.set_bitrate(args.bitrate)
	else:
		print(bb.get_bitrate())

@subcommand("get or set device modulation index")
@argument('modindex', type=int, help="requested modulation index", nargs="?", default=None)
def modindex(args, bb):
	if args.modindex is not None:
		bb.set_modindex(args.modindex)
	else:
		print(bb.get_modindex())

@subcommand("get or set device training sequence")
@argument('length', type=int, help="training sequence length in ms", nargs="?", default=None)
def training(args, bb):
	if args.length is not None:
		bb.set_training(args.length)
	else:
		print(bb.get_training())

@subcommand("get or set device power level")
@argument('power', type=parse_power, help="power level 0-63 (ADF702x PA setting, not in dBm!)", nargs="?", default=None)
def power(args, bb):
	if args.power is not None:
		bb.set_power(args.power)
	else:
		print(bb.get_power())

@subcommand("get or set device CSMA level in dBm")
@argument('level', type=int, help="CSMA level in dBm", nargs="?", default=None)
def csma(args, bb):
	if args.level is not None:
		bb.set_csma(args.level)
	else:
		print(bb.get_csma())

@subcommand("basic spectrum analysis")
@argument("-c", metavar="center", dest="center", type=parse_frequency, help="center frequency in Hz", default=str(437.45e6))
@argument("-s", metavar="span", dest="span", type=parse_frequency, help="frequency span in Hz", default=str(5e3))
@argument("-b", metavar="bins", dest="bins", type=int, help="number of bins to divide span in", default=10)
@argument("-t", metavar="samples", dest="samples", type=int, help="number of samples per frequency", default=10)
def spectrum(args, bb):
	import curses

	center = args.center
	span = args.span
	bins = args.bins

	if center - span < 0:
		raise Exception("Invalid span")

	stdscr = curses.initscr()
	curses.noecho()
	curses.cbreak()
	stdscr.nodelay(1)
	curses.curs_set(0)

	while True:
		try:
			stdscr.erase()
			stdscr.addstr("showing spectrum from {0} Hz to {1} Hz in {2} bins\n\n".format(
								center-span//2, center+span//2, bins))
			orig_freq = bb.get_frequency()
			for freq in range(center - span//2, center + span//2+1, span//bins):
				bb.set_frequency(freq)
				rssi = bb.rssi(args.samples)
				stdscr.addstr("{0}: {1} {2} dBm\n".format(freq, bar(rssi), rssi))
			bb.set_frequency(orig_freq)
			stdscr.refresh()
		except KeyboardInterrupt:
			break
		except Exception as e:
			print(e)
			break
		finally:
			if stdscr.getch() >= 0:
				break

	curses.curs_set(1)
	curses.nocbreak();
	stdscr.keypad(0);
	curses.echo()
	curses.endwin()

@subcommand("set ADF7021 register")
@argument("register", type=parse_int, help="register number to write")
@argument("value", type=parse_int, help="new register value")
def register(args, bb):
	bb.reg_write(args.register, (args.value << 8))

@subcommand("show detailed help for subcommand")
@argument('command', help="detailed help command", nargs="?", default=None)
def help(args, parser):
	if args.command is not None:
		subcommands[args.command]["parser"].print_help()
	else:
		parser.print_help()

@subcommand("list all connected devices with status")
def list(args):
	index = 0

	header = "Index  USB path  Frequency  Bitrate  Modindex  Power  Train  Transmit  Receive"
	fields = "{0:<5}  {1:<03}:{2:<03}   {3:<9}  {4:<7}  {5:<8}  {6:<5}  {7:<5}  {8:<8}  {9:<7}"

	while True:
		try:
			bb = bluebox.Bluebox(index=index)
			if index == 0:
				print(header)
			print(fields.format(
				index,
				bb.dev.bus,
				bb.dev.address,
				bb.get_frequency(),
				bb.get_bitrate(),
				bb.get_modindex(),
				bb.get_power(),
				bb.get_training(),
				bb.get_transmitted(),
				bb.get_received()))
		except Exception as e:
			if index == 0:
				print("Error: no BlueBox found")
			break
		finally:
			index += 1


class SubcommandHelpFormatter(argparse.RawDescriptionHelpFormatter):
	def _format_action(self, action):
		parts = super(argparse.RawDescriptionHelpFormatter, self)._format_action(action)
		if action.nargs == argparse.PARSER:
			parts = parts.split("\n")
			parts = ["   "+"  ".join(part.lstrip().split(" ", 1)) for part in parts[1:]]
			parts = "\n".join(parts)
		return parts

desc = """
Main BlueBox satellite ground station control program. %(prog)s is used for
controlling frequency, bitrate, etc. of the device and to transmit and
receive data.

The BlueBox firmware and bbctl is free software licensed under the MIT license.
For more information see http://www.satlab.org or http://github.com/satlab

"""

epilog="See '%(prog)s help <command>' for more information on a specific command."

def main():
	global enable_colors
	parser = argparse.ArgumentParser(description=desc, epilog=epilog, formatter_class=SubcommandHelpFormatter)
	parser.add_argument("-i", metavar="<index>", dest="index", default=0, type=int, help="select specific BlueBox device")
	parser.add_argument("-t", metavar="<timeout>", dest="timeout", type=int, default=10000, help="set transfer timeout in ms")
	parser.add_argument("-v", "--verbose", action="store_true", help="enable verbose output")
	parser.add_argument("-w", "--wait", action="store_true", help="wait for device if not connected")
	parser.add_argument("-c", "--no-color", action="store_false", dest="color", help="disable color output")
	subparsers = parser.add_subparsers(dest="subparser", title="The available subcommands are", metavar="<command>")

	for sub in sorted(subcommands):
		args, kwargs = subcommands[sub]["sub"]
		subparser = subparsers.add_parser(*args, formatter_class=SubcommandHelpFormatter, **kwargs)
		subcommands[sub]["parser"] = subparser
		for args, kwargs in subcommands[sub]["args"]:
			arg = args[0] if kwargs.get("nargs", "") == "?" else "<" + args[0] + ">"
			if not args[0].startswith("-"):
				kwargs["metavar"] = kwargs.get("metavar", arg)
			subparser.add_argument(*args, **kwargs)
		subparser.set_defaults(func=subcommands[sub]["func"])

	if len(sys.argv) < 2:
		parser.print_help()
		sys.exit(1)

	if not sys.argv[1].startswith("-") and not sys.argv[1] in subcommands:
		print("{0}: '{1}' is not a {0} command. See '{0} --help'.".format(parser.prog, sys.argv[1]))
		sys.exit(1)

	args = parser.parse_args()
	if args.func == help:
		args.func(args, parser)
		sys.exit(0)

	if args.func == list:
		args.func(args)
		sys.exit(0)

	enable_colors = args.color

	try:
		bb = bluebox.Bluebox(index=args.index, wait=args.wait, timeout=args.timeout)
	except KeyboardInterrupt:
		print()
		sys.exit(0)
	except Exception as e:
		print("Failed to connect to BlueBox: {0}".format(e))
		sys.exit(0)

	if args.verbose:
		print("Found {0} {1} with serial {2} on bus {3}:{4}".format(
		      bb.manufacturer, bb.product, bb.serial, bb.bus, bb.address))

	try:
		args.func(args, bb)
	except Exception as e:
		print("Error: {0}".format(str(e)))
	except KeyboardInterrupt:
		print()
	sys.exit(0)

if __name__ == "__main__":
	main()
